<a href="https://colab.research.google.com/github/jaydigy/jayg_colab_gate/blob/main/ak_nanogpt_by_jayg.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Andrej Kapathy nanoGPT 코딩 따라하기 from scratch by kjg : generative pre-trained trasformer


In [1]:
!wget 'https://raw.githubusercontent.com/karpathy/char-rnn/master/data/tinyshakespeare/input.txt'

--2023-05-07 06:00:53--  https://raw.githubusercontent.com/karpathy/char-rnn/master/data/tinyshakespeare/input.txt
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.109.133, 185.199.108.133, 185.199.110.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.109.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 1115394 (1.1M) [text/plain]
Saving to: ‘input.txt’

input.txt           100%[===================>]   1.06M  --.-KB/s    in 0.006s  

2023-05-07 06:00:53 (176 MB/s) - ‘input.txt’ saved [1115394/1115394]



In [2]:
# read it in to inspect it
with open('input.txt', 'r', encoding='utf-8') as f:
    text = f.read()

In [3]:
print("length of dataset in chracters: ", len(text))

length of dataset in chracters:  1115394


In [4]:
# let's look at the first 1000 characters
print(text[:1000])

First Citizen:
Before we proceed any further, hear me speak.

All:
Speak, speak.

First Citizen:
You are all resolved rather to die than to famish?

All:
Resolved. resolved.

First Citizen:
First, you know Caius Marcius is chief enemy to the people.

All:
We know't, we know't.

First Citizen:
Let us kill him, and we'll have corn at our own price.
Is't a verdict?

All:
No more talking on't; let it be done: away, away!

Second Citizen:
One word, good citizens.

First Citizen:
We are accounted poor citizens, the patricians good.
What authority surfeits on would relieve us: if they
would yield us but the superfluity, while it were
wholesome, we might guess they relieved us humanely;
but they think we are too dear: the leanness that
afflicts us, the object of our misery, is as an
inventory to particularise their abundance; our
sufferance is a gain to them Let us revenge this with
our pikes, ere we become rakes: for the gods know I
speak this in hunger for bread, not in thirst for revenge.



여기서 아랫 부분 일부는 한글을 읽어서 엔코드 데코드 체크해봄

In [ ]:
# from google.colab import files
# uploaded = files.upload()

# with open('data.txt', 'r') as f:
#     text = f.read()

# print("length of dataset in chracters: ", len(text))
# # let's look at the first 1000 characters
# print(text[:1000])



In [81]:
# text = "6일 방송된 KBS 2TV 주말드라마 진짜가 나타났다(극본 조정주/연출 한준서)에서는 오연두(백진희 분)가 입덧을 시작했다. 별채에 몰래 들어간 장세진(차주영 분)은 오연두의 산모수첩을 보고, 3개월이면 끝이라고 적힌 메모에 의심을 품었다. 별채를 나가려는데 오연두와 공태경(안재현 분)이 들어오는 소리를 듣고 황급히 베란다에 숨었다. 공태경은 오연두에게 생일 선물로 미아 방지 팔찌를 선물했다. 장세진은 별채에서 조용히 빠져나왔다. 집에 돌아간 장세진은 오연두의 메모가 무슨 의미인지 알아채진 못했지만, 자기가 해놓은 그대로인 별채 인테리어가 아무래도 이상하다고 생각했다. 오동욱(최윤제 분)은 공태경을 가족 단체 채팅방에 초대했다. 자다가 깬 공태경은 짜증을 내면서도 답을 해야 하는지 고민했다. 공태경은 사위 노릇을 하기로 하고 답장을 했다. 오연두는 배가 고파서 잠에서 깼다. 그런데 냉장고에 반찬이 없자 본채에 몰래 들어갔다가 은금실(강부자 분)에게 들키고 말았다. 은금실은 자기 손주들 먹이려고 만든 거라며 이리 내놓으라고 했고 오연두는 안 주려고 버티다가 김치 국물을 뒤집어쓰고 말았다."


In [19]:
# print(text)

6일 방송된 KBS 2TV 주말드라마 진짜가 나타났다(극본 조정주/연출 한준서)에서는 오연두(백진희 분)가 입덧을 시작했다. 별채에 몰래 들어간 장세진(차주영 분)은 오연두의 산모수첩을 보고, 3개월이면 끝이라고 적힌 메모에 의심을 품었다. 별채를 나가려는데 오연두와 공태경(안재현 분)이 들어오는 소리를 듣고 황급히 베란다에 숨었다. 공태경은 오연두에게 생일 선물로 미아 방지 팔찌를 선물했다. 장세진은 별채에서 조용히 빠져나왔다. 집에 돌아간 장세진은 오연두의 메모가 무슨 의미인지 알아채진 못했지만, 자기가 해놓은 그대로인 별채 인테리어가 아무래도 이상하다고 생각했다. 오동욱(최윤제 분)은 공태경을 가족 단체 채팅방에 초대했다. 자다가 깬 공태경은 짜증을 내면서도 답을 해야 하는지 고민했다. 공태경은 사위 노릇을 하기로 하고 답장을 했다. 오연두는 배가 고파서 잠에서 깼다. 그런데 냉장고에 반찬이 없자 본채에 몰래 들어갔다가 은금실(강부자 분)에게 들키고 말았다. 은금실은 자기 손주들 먹이려고 만든 거라며 이리 내놓으라고 했고 오연두는 안 주려고 버티다가 김치 국물을 뒤집어쓰고 말았다.


In [20]:
# # here are all the unique chractesrs that occur in thins text
# chars = sorted(list(set(text)))
# vocab_size = len(chars)
# print(''.join(chars))
# print(vocab_size)

 (),./236BKSTV가각간갔강개거게경고공국그극금급기김깬깼끝나났내냉노놓는다단답대덧데도돌동된두뒤드든듣들라란래런려로를릇리마만말먹메며면모몰못무물미민반방배백버베별보본부분빠사산상생서선세소손송수숨슨시실심쓰아안알았야어없었에연영오와왔용욱월위윤으은을의이인일입자작잠장재적정제져조족주준증지진집짜찌차찬채첩체초최출치키타태테티팅파팔품하한해했현황희히힌
183


In [21]:
# # create a mapping from characters to integers
# stoi = { ch:i for i, ch in enumerate(chars)}
# itos = { i:ch for i, ch in enumerate(chars)}
# encode = lambda s: [stoi[c] for c in s] #encoder : take a string, output a list of integers
# decode = lambda l: ''.join([itos[i] for i in l]) # decoder : take a list of integers, output a string

# print(encode("답도 놓는다"))
# print(decode(encode("답도 놓는다")))

[44, 48, 0, 40, 41, 42]
답도 놓는다


한글 텍스트 엔코드 데코드 체크는 여기까지

In [5]:
# here are all the unique chractesrs that occur in thins text
chars = sorted(list(set(text)))
vocab_size = len(chars)
print(''.join(chars))
print(vocab_size)


 !$&',-.3:;?ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz
65


In [6]:
# create a mapping from characters to integers
stoi = { ch:i for i, ch in enumerate(chars)}
itos = { i:ch for i, ch in enumerate(chars)}
encode = lambda s: [stoi[c] for c in s] #encoder : take a string, output a list of integers
decode = lambda l: ''.join([itos[i] for i in l]) # decoder : take a list of integers, output a string

print(encode("hii there"))
print(decode(encode("hii there")))

[46, 47, 47, 1, 58, 46, 43, 56, 43]
hii there


In [7]:
# let's now encode the entire text dataset and store it into a torch.Tensor
import torch #we use PyTorch:https://pytorch.org
data = torch.tensor(encode(text), dtype=torch.long)
print(data.shape, data.dtype)
print(data[:1000]) # the 1000 characters we looked at earlier will to the GPT look like this

torch.Size([1115394]) torch.int64
tensor([18, 47, 56, 57, 58,  1, 15, 47, 58, 47, 64, 43, 52, 10,  0, 14, 43, 44,
        53, 56, 43,  1, 61, 43,  1, 54, 56, 53, 41, 43, 43, 42,  1, 39, 52, 63,
         1, 44, 59, 56, 58, 46, 43, 56,  6,  1, 46, 43, 39, 56,  1, 51, 43,  1,
        57, 54, 43, 39, 49,  8,  0,  0, 13, 50, 50, 10,  0, 31, 54, 43, 39, 49,
         6,  1, 57, 54, 43, 39, 49,  8,  0,  0, 18, 47, 56, 57, 58,  1, 15, 47,
        58, 47, 64, 43, 52, 10,  0, 37, 53, 59,  1, 39, 56, 43,  1, 39, 50, 50,
         1, 56, 43, 57, 53, 50, 60, 43, 42,  1, 56, 39, 58, 46, 43, 56,  1, 58,
        53,  1, 42, 47, 43,  1, 58, 46, 39, 52,  1, 58, 53,  1, 44, 39, 51, 47,
        57, 46, 12,  0,  0, 13, 50, 50, 10,  0, 30, 43, 57, 53, 50, 60, 43, 42,
         8,  1, 56, 43, 57, 53, 50, 60, 43, 42,  8,  0,  0, 18, 47, 56, 57, 58,
         1, 15, 47, 58, 47, 64, 43, 52, 10,  0, 18, 47, 56, 57, 58,  6,  1, 63,
        53, 59,  1, 49, 52, 53, 61,  1, 15, 39, 47, 59, 57,  1, 25, 39, 56, 41,
      

In [8]:
#Let's now split up the data into train and validation sets
n = int(0.9*len(data)) # first 90% will be train, rest val
train_data = data[:n]
val_data = data[n:]

In [9]:
block_size = 8
train_data[:block_size+1]

tensor([18, 47, 56, 57, 58,  1, 15, 47, 58])

In [10]:
x = train_data[:block_size]
y = train_data[1:block_size+1] #y는 각위치에서의 target 이다. 
for t in range(block_size):
    context = x[:t+1]
    target = y[t]
    print(f"when input is {context} the target: {target}")

when input is tensor([18]) the target: 47
when input is tensor([18, 47]) the target: 56
when input is tensor([18, 47, 56]) the target: 57
when input is tensor([18, 47, 56, 57]) the target: 58
when input is tensor([18, 47, 56, 57, 58]) the target: 1
when input is tensor([18, 47, 56, 57, 58,  1]) the target: 15
when input is tensor([18, 47, 56, 57, 58,  1, 15]) the target: 47
when input is tensor([18, 47, 56, 57, 58,  1, 15, 47]) the target: 58


In [11]:
torch.manual_seed(1337)
batch_size = 4 # how many independent sequences will we process in parallel?
block_size = 8 # what is the maximum conteext length for prediction?

def get_batch(split):
    #generate a small batch of data of inputs x and targets y
    data = train_data if split == 'train' else val_data
    ix = torch.randint(len(data) - block_size, (batch_size,))
    x = torch.stack([data[i:i+block_size] for i in ix])
    y = torch.stack([data[i+1:i+block_size+1] for i in ix])
    return x, y

xb, yb = get_batch('train')
print('inputs:')
print(xb.shape)
print(xb)
print('targets:')
print(yb.shape)
print(yb)

print('---------')

for b in range(batch_size): #batch dimension
    for t in range(block_size): #time dimension
        context = xb[b, :t+1]
        target = yb[b,t]
        print(f"when input is {context.tolist()} the target: {target}")
         


inputs:
torch.Size([4, 8])
tensor([[24, 43, 58,  5, 57,  1, 46, 43],
        [44, 53, 56,  1, 58, 46, 39, 58],
        [52, 58,  1, 58, 46, 39, 58,  1],
        [25, 17, 27, 10,  0, 21,  1, 54]])
targets:
torch.Size([4, 8])
tensor([[43, 58,  5, 57,  1, 46, 43, 39],
        [53, 56,  1, 58, 46, 39, 58,  1],
        [58,  1, 58, 46, 39, 58,  1, 46],
        [17, 27, 10,  0, 21,  1, 54, 39]])
---------
when input is [24] the target: 43
when input is [24, 43] the target: 58
when input is [24, 43, 58] the target: 5
when input is [24, 43, 58, 5] the target: 57
when input is [24, 43, 58, 5, 57] the target: 1
when input is [24, 43, 58, 5, 57, 1] the target: 46
when input is [24, 43, 58, 5, 57, 1, 46] the target: 43
when input is [24, 43, 58, 5, 57, 1, 46, 43] the target: 39
when input is [44] the target: 53
when input is [44, 53] the target: 56
when input is [44, 53, 56] the target: 1
when input is [44, 53, 56, 1] the target: 58
when input is [44, 53, 56, 1, 58] the target: 46
when input is [4

In [12]:
print(xb) #our input th the transformer

tensor([[24, 43, 58,  5, 57,  1, 46, 43],
        [44, 53, 56,  1, 58, 46, 39, 58],
        [52, 58,  1, 58, 46, 39, 58,  1],
        [25, 17, 27, 10,  0, 21,  1, 54]])


In [13]:
import torch
import torch.nn as nn
from torch.nn import functional as F
torch.manual_seed(1337)

class BigramLanguageModel(nn.Module):

    def __init__(self, vocab_size):
        super().__init__()
        #each token directly reads off the logits for the next token from a lookup table
        self.token_embedding_table = nn.Embedding(vocab_size, vocab_size)

    def forward(self, idx, targets=None):

        #idx and targets are both (B batch, T time) tensor of integers
        logits = self.token_embedding_table(idx) # (B batch 4, T time 8, C channel 65)
        if targets is None:
            loss = None
        else:
            B, T, C = logits.shape
            logits = logits.view(B*T, C)
            targets = targets.view(B*T)   
            loss = F.cross_entropy(logits, targets)

        return logits, loss

    def generate(self, idx, max_new_tokens):
        #idx is (B, T) array of indices in the current context
        for _ in range(max_new_tokens):
            #get the predictions
            logits, loss = self(idx)
            #focus onlt on the last time step
            logits = logits[:, -1, :] #becomes (B,c)
            #apply softmax to get probabilities
            probs = F.softmax(logits, dim=-1) # (B,c)
            #sample from the distribution
            idx_next = torch.multinomial(probs, num_samples=1) #(B,1)
            #eppend smapled index to the running sequence
            idx = torch.cat((idx, idx_next), dim=1) # (B, T+1)
        return idx

m = BigramLanguageModel(vocab_size)
logits, loss = m(xb, yb)
# logits, loss = m(xb, yb)
# print(logits, loss)
# print(out)
print(logits.shape)
print(loss)

print(decode(m.generate(idx = torch.zeros((1,1), dtype=torch.long), max_new_tokens=100)[0].tolist()))

torch.Size([32, 65])
tensor(4.8786, grad_fn=<NllLossBackward0>)

Sr?qP-QWktXoL&jLDJgOLVz'RIoDqHdhsV&vLLxatjscMpwLERSPyao.qfzs$Ys$zF-w,;eEkzxjgCKFChs!iWW.ObzDnxA Ms$3


In [14]:
#create a PyTorch optimizer
optimizer = torch.optim.Adam(m.parameters(), lr=1e-3)

In [17]:
batch_size = 32
for steps in range(20000):

    #sample a batch of data
    xb, yb = get_batch('train')

    #evaluate the loss
    logits, loss = m(xb, yb)
    optimizer.zero_grad(set_to_none=True)
    loss.backward()
    optimizer.step()

print(loss.item())


2.399700403213501


In [19]:
print(decode(m.generate(idx = torch.zeros((1,1), dtype=torch.long), max_new_tokens=500)[0].tolist()))


Hegorer:
'd
NGELO: hare be thand, am It jue ouch!
I inil!-ile ithar akeak Peamyol I

Fome.
To owerithe pthacaivisut lle?
Casll antes whthitlf,
Tolfan the thee.
Whadsha moce t.
ARDUS:
THES:
DWh; I an HAnon l by nourlfighofovy fader? VES:
PAUNT:
My.
he is s OFo'T:
mmporche? l athorit, chot Ang ixis, ale s, oor fr INTofendyepre busucave d; awo ithitheay savoultoo heancitand
A n, jethest? kize ingor t tll n:
Kist'Th ith thar whath trel, bulyo go tou le an htous sthous topl me wond,
LApe!
I
I fith is


이제 트랜스포머의 어텐션 영역으로 들어감

셀프 어텐션 기법의 수학적 특징 : youtube 42분 20초

In [21]:
# consider the following toy example:

torch.manual_seed(1337)
B, T, C = 4, 8, 2 # Batch, Time, Channels
x = torch.randn(B, T, C)
x.shape
x

tensor([[[ 0.1808, -0.0700],
         [-0.3596, -0.9152],
         [ 0.6258,  0.0255],
         [ 0.9545,  0.0643],
         [ 0.3612,  1.1679],
         [-1.3499, -0.5102],
         [ 0.2360, -0.2398],
         [-0.9211,  1.5433]],

        [[ 1.3488, -0.1396],
         [ 0.2858,  0.9651],
         [-2.0371,  0.4931],
         [ 1.4870,  0.5910],
         [ 0.1260, -1.5627],
         [-1.1601, -0.3348],
         [ 0.4478, -0.8016],
         [ 1.5236,  2.5086]],

        [[-0.6631, -0.2513],
         [ 1.0101,  0.1215],
         [ 0.1584,  1.1340],
         [-1.1539, -0.2984],
         [-0.5075, -0.9239],
         [ 0.5467, -1.4948],
         [-1.2057,  0.5718],
         [-0.5974, -0.6937]],

        [[ 1.6455, -0.8030],
         [ 1.3514, -0.2759],
         [-1.5108,  2.1048],
         [ 2.7630, -1.7465],
         [ 1.4516, -1.5103],
         [ 0.8212, -0.2115],
         [ 0.7789,  1.5333],
         [ 1.6097, -0.4032]]])

In [ ]:
# we want x[b,t] = mean_{i<=t} *[b, i]
xbow = torch.zeros((B, T, C))
for b in range(B):
    for t in range(T):
        xprev = x[b,:t+1] #(t,c)
        # print(xprev)
        xbow[b,t] = torch.mean(xprev, 0)
        print(xbow[b,t])

In [37]:
#version 2
wei = torch.tril(torch.ones(T, T))
wei = wei / wei.sum(1, keepdim=True)
xbow2 = wei @  x #(B ,T, T) @ (B, T, C) ----> (B, T, C)
torch.allclose(xbow, xbow2)

True

In [41]:
#version 3
tril = torch.tril(torch.ones(T, T))
wei = torch.zeros((T, T))
wei = wei.masked_fill(tril == 0, float('-inf'))
wei = F.softmax(wei, dim=-1)
xbow3 = wei @ x 
torch.allclose(xbow, xbow3)

True

셀프 어텐션 기법 설명 : 아래는 x라는 모집단에서 k와 q를 나눠서 서로 인디펜던트 하게 데이타 만들고 합성곱일때만 서로 기여도 파악을 한다. 
멀티 헤드 어텐션은 x 집단의 k와 다른 집단의 q가 서로 어텐션을 해서 기여도를 파악할수 있는 구조이다. 멀티헤드로 데이터를 배치 작업을 해서 각각 패럴렐로
따로 gpu에서 돌리다가 하나의 gpu에 있는 k와 다른 gpu에 있는 q가 서로 어텐션을 하고 참고를 하는 구조이다. 

In [65]:
#version 4 : self attention -> youttube 비디오 1:02:14
torch.manual_seed(1337)
B, T, C = 4, 8, 32 #batch, time, channels
x= torch.randn(B, T, C)


#query : what i'm looking for, key : what i'm having
#let's see a single head perform self-attention
head_size = 16
key = nn.Linear(C, head_size, bias=False)
query = nn.Linear(C, head_size, bias=False)
value = nn.Linear(C, head_size, bias=False)
k = key(x) # (B, T, 16) -> 16은 헤드 사이즈
q = query(x) #(B, T, 16) -> 16은 헤드사이즈
# key와 query가 커뮤니케이션이 없음
wei = q @ k.transpose(-2, -1) # (B, T, 16) @ (B, 16, T) ---> (B, T, T) -> key와 query가 커뮤니케이션 시작


tril = torch.tril(torch.ones(T, T))
# wei = torch.zeros((T, T))
wei = wei.masked_fill(tril == 0, float('-inf'))
wei = F.softmax(wei, dim=-1)
# out = wei @ x 

v = value(x)
out = wei @ v

out.shape
# out[0]

torch.Size([4, 8, 16])

In [66]:
wei

tensor([[[1.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
         [0.1574, 0.8426, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
         [0.2088, 0.1646, 0.6266, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
         [0.5792, 0.1187, 0.1889, 0.1131, 0.0000, 0.0000, 0.0000, 0.0000],
         [0.0294, 0.1052, 0.0469, 0.0276, 0.7909, 0.0000, 0.0000, 0.0000],
         [0.0176, 0.2689, 0.0215, 0.0089, 0.6812, 0.0019, 0.0000, 0.0000],
         [0.1691, 0.4066, 0.0438, 0.0416, 0.1048, 0.2012, 0.0329, 0.0000],
         [0.0210, 0.0843, 0.0555, 0.2297, 0.0573, 0.0709, 0.2423, 0.2391]],

        [[1.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
         [0.1687, 0.8313, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
         [0.2477, 0.0514, 0.7008, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
         [0.4410, 0.0957, 0.3747, 0.0887, 0.0000, 0.0000, 0.0000, 0.0000],
         [0.0069, 0.0456, 0.0300, 0.7748, 0.1427, 0.0000, 0.0000, 0.0000],
         [0.0660, 0.089

In [74]:
k = torch.randn(B,T, head_size)
q = torch.randn(B,T, head_size)
wei = q @ k.transpose(-2, -1) * head_size**-0.5

In [71]:
k.var() #데이터으 분산을 구함

tensor(1.0449)

In [72]:
q.var()

tensor(1.0700)

In [75]:
wei.var()

tensor(0.9957)

참고 논문 추가 설명 in youtube
1. Deep Residual Learning for Image Recognition -> 1:28:44
   : self attention 논문의 add & Norm 설명하는 논문으로 일부 데이터를 레이어 거치지 않고 바로 아웃풋으로 직행 시켜서 합해서 계산에 활용

2. layernorm : pytouch document-> 1:33:07
 :add&norm에서 norm의 기능을 ak가 기존 transformer에 추가함

3. dropout : a simple way to prevent neural networks fromm overfitting -> 1:38:45
-> 포워드 및 백워드에서 임이의 데이터 셋을 삭제하여, overfitting을 방지한다. 

4. 본 프로그램은 decode만 있고, 트랜스포머 논문의 encoder 기능은 없다. 1:45:30
: 트랜스포머의 인코더에서는 불어를 이용해 토큰을 만들고, 토큰은 서로 allowed to talk as much as they want, key와 values 는 인코더 단계에서 만들어져서 멀티어틴션에 크로스 어텐션에 들어간다. query는 x에서 만들어지지만, key와 value가 인코더에서 만들어져서 옆으로 들어오는 특징이 있다.들어온 값이  multi-head attention의 x 집단에 뿌려진다.  



nanoGPT github 설명 -> 1:46:29
GPT3 Paper : Language Models are Few-Shot Learners : 1:50:17
chatGPT -> 
1. 처음에 인터넷 상에 있는 모든 텍스트를 pre-train stage에서 본 코드에 있는바와 같이 트랜스포머의 decoder 만 이용을 했다. 
2. 2nd fine-tunning stage -> openat에 설명서 있음 : 3단계의 슈퍼바이즈드 스코어링을 했고, 이 데이터는 오픈안된다. 


In [59]:
print(k)

tensor([[[ 1.1965e-01, -3.0127e-01,  3.6293e-01,  1.1771e+00,  1.1385e+00,
          -2.5543e-01,  1.4537e-01, -2.9437e-01, -7.0201e-01, -1.0308e+00,
           7.4357e-01, -8.0984e-01, -6.6687e-01,  9.1233e-02, -6.0747e-03,
           1.9833e-01],
         [-5.4229e-01, -5.5581e-01, -7.6131e-02,  1.2929e+00,  8.6535e-01,
          -1.1998e+00,  3.8781e-01,  1.9389e-01,  7.0235e-01, -8.2251e-01,
           2.3484e-01, -8.4995e-01, -3.8126e-01, -2.9906e-01,  1.0242e-02,
          -5.5449e-01],
         [-3.7359e-01, -4.6781e-01, -2.1560e-01, -8.0344e-01, -3.7153e-01,
          -5.4427e-01, -9.1455e-01, -5.5926e-02, -3.2903e-01, -2.1023e-01,
           1.1665e-01, -1.7978e-01, -2.8196e-01, -3.3204e-01, -4.5963e-01,
          -1.3255e-01],
         [-3.1463e-01,  8.4460e-02, -1.2351e-01, -7.0577e-01, -1.8022e-01,
           5.4922e-01, -8.9805e-01, -4.9384e-01,  6.7907e-01,  8.8270e-01,
           4.9109e-01,  5.1903e-01,  9.0109e-01,  9.1255e-02, -1.9332e-01,
          -6.7704e-01],
    

In [51]:
xbow[0], xbow2[0], xbow3[0]

(tensor([[ 0.1808, -0.0700],
         [-0.0894, -0.4926],
         [ 0.1490, -0.3199],
         [ 0.3504, -0.2238],
         [ 0.3525,  0.0545],
         [ 0.0688, -0.0396],
         [ 0.0927, -0.0682],
         [-0.0341,  0.1332]]),
 tensor([[ 0.1808, -0.0700],
         [-0.0894, -0.4926],
         [ 0.1490, -0.3199],
         [ 0.3504, -0.2238],
         [ 0.3525,  0.0545],
         [ 0.0688, -0.0396],
         [ 0.0927, -0.0682],
         [-0.0341,  0.1332]]),
 tensor([[ 0.1808, -0.0700],
         [-0.0894, -0.4926],
         [ 0.1490, -0.3199],
         [ 0.3504, -0.2238],
         [ 0.3525,  0.0545],
         [ 0.0688, -0.0396],
         [ 0.0927, -0.0682],
         [-0.0341,  0.1332]]))

In [47]:
wei = torch.zeros((T, T))
wei = wei.masked_fill(tril == 0, float('-inf'))
wei = F.softmax(wei, dim=-1)
wei

tensor([[1.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.5000, 0.5000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.3333, 0.3333, 0.3333, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.2500, 0.2500, 0.2500, 0.2500, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.2000, 0.2000, 0.2000, 0.2000, 0.2000, 0.0000, 0.0000, 0.0000],
        [0.1667, 0.1667, 0.1667, 0.1667, 0.1667, 0.1667, 0.0000, 0.0000],
        [0.1429, 0.1429, 0.1429, 0.1429, 0.1429, 0.1429, 0.1429, 0.0000],
        [0.1250, 0.1250, 0.1250, 0.1250, 0.1250, 0.1250, 0.1250, 0.1250]])

In [40]:
xbow[1], xbow2[1]

(tensor([[ 1.3488, -0.1396],
         [ 0.8173,  0.4127],
         [-0.1342,  0.4395],
         [ 0.2711,  0.4774],
         [ 0.2421,  0.0694],
         [ 0.0084,  0.0020],
         [ 0.0712, -0.1128],
         [ 0.2527,  0.2149]]),
 tensor([[ 1.3488, -0.1396],
         [ 0.8173,  0.4127],
         [-0.1342,  0.4395],
         [ 0.2711,  0.4774],
         [ 0.2421,  0.0694],
         [ 0.0084,  0.0020],
         [ 0.0712, -0.1128],
         [ 0.2527,  0.2149]]))

In [30]:
xbow[0]

tensor([[ 0.1808, -0.0700],
        [-0.0894, -0.4926],
        [ 0.1490, -0.3199],
        [ 0.3504, -0.2238],
        [ 0.3525,  0.0545],
        [ 0.0688, -0.0396],
        [ 0.0927, -0.0682],
        [-0.0341,  0.1332]])

In [34]:
torch.manual_seed(42)
# a = torch.ones(3, 3)
a = torch.tril(torch.ones(3, 3))
a = a /torch.sum(a, 1, keepdim=True)
b = torch.randint(0, 10, (3, 2)).float()
c = a @ b #multiply -> 행렬곱을 나타냄
print('a=')
print(a)
print('--')
print('b=')
print(b)
print('c=')
print(c)


a=
tensor([[1.0000, 0.0000, 0.0000],
        [0.5000, 0.5000, 0.0000],
        [0.3333, 0.3333, 0.3333]])
--
b=
tensor([[2., 7.],
        [6., 4.],
        [6., 5.]])
c=
tensor([[2.0000, 7.0000],
        [4.0000, 5.5000],
        [4.6667, 5.3333]])
